id: PB4AEBAB4
initial_creation_type: input
source_metadata:
  title: Saving Lives Series
  language: en
  description: 'The following texts are currently available as part of our Saving
    Lives series:'
  volume:
    a5eb64c340724bfca88a5be8bee3f6ae:
      title: 'The Stairway to Great Bliss: A Method for Planting the Seed of Liberation
        in Animals'
      parent: Practices
    039169821fb04a66887f3a1b394dceef:
      title: 'The Essence of Benefit and Happiness: A Method for Saving Lives'
      parent: Practices
    838f9ffef2ae4c14ba85b525bf15ed54:
      title: 'Increasing Life and Vitality: A Practice for Freeing Lives'
      parent: Practices
    333d3c9d5ff847e4a4a9fb8d636b6a02:
      title: 'A River Filled with the Amṛta of Love: A Liturgy for Saving and Releasing
        the Lives of Animals'
      parent: Practices
    e042a6edb5c34853802357968056568f:
      title: 'The Glorious Gift of Longevity and Granting All Desires: A Liturgy for
        Saving Lives'
      parent: Practices
    f91fcc22d951442090168e44acf2fb57:
      title: The Benefits of Saving Lives
      parent: Commentaries
created_at: '2022-03-01T05:42:44.272085'
last_modified_at: '2022-03-01T05:42:44.272091'
